version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/openjdk:10-jdk-node-browsers
        environment:
              TERM: dumb
    environment:
      JVM_OPTS: -Xmx4800m
    steps:
      - checkout
      - restore_cache:
          key: cache-{{ checksum "build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: cache-{{ checksum "build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew check
      - run:
          name: Save test results 
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - run:
          command: ./gradlew jacocoTestReport
      - codecov/upload:
          file: ./build/reports/jacoco/test/jacocoTestReport.xml
      - store_artifacts:
          path: ~/junit
      - run:
          name: Build Artifacts
          command: ./gradlew assemble shadowJar
      - persist_to_workspace:
          root: ~/
          paths: 
            - code
  deploy:
    working_directory: ~/code
    docker:
      - image: circleci/openjdk:10-jdk-node-browsers
    steps:      
      - attach_workspace:
          at: ~/
      - setup_remote_docker
      - run: |
          TAG=1.0.$CIRCLE_BUILD_NUM          
          docker build -t thcathy/strava-activity-uploader:latest -t thcathy/strava-activity-uploader:$TAG .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push thcathy/strava-activity-uploader:latest
          docker push thcathy/strava-activity-uploader:$TAG
workflows:
  version: 2
  commit-workflow:
    jobs:
      - build 
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master