FROM arm64v8/openjdk:11
ADD ./release/strava-activity-uploader.jar /app.jar
ENTRYPOINT ["java","-Dstrava.client_id=$STRAVA_CLIENT_ID -Dstrava.client_secret=$STRAVA_CLIENT_SECRET -Dmail.host=$MAIL_HOST -Dmail.username=$MAIL_USERNAME -Dmail.password=$MAIL_PASSWORD","-jar","/app.jar","-Xmx512m -XX:+UseConcMarkSweepGC -XX:+PrintGCDetails -XX:+PrintHeapAtGC"]